"""
autoreport.py
Scheduled version of the pipeline: computes metrics, generates the AI
report, saves a dated copy to output/, and emails it. Run this from cron /
Task Scheduler / GitHub Actions for the "weekly report" use case described
in the README. For a one-off report without email, use insight_generator.py.
"""
import os
import smtplib
from datetime import datetime
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

from dotenv import load_dotenv
from groq import Groq

from metrics import compute_metrics, format_metrics_summary, generate_ai_report, load_data

load_dotenv()


def build_html_email(m: dict, ai_report: str, today: str) -> str:
    loss_row_style = "background-color: #fff3e0;"
    return f"""
<html>
<body style="font-family: Arial, sans-serif; max-width: 700px; margin: auto;">

  <div style="background-color: #1F4E79; padding: 20px; border-radius: 8px 8px 0 0;">
    <h1 style="color: white; margin: 0; font-size: 22px;">
      Weekly Business Insight Report
    </h1>
    <p style="color: #ACD4EE; margin: 5px 0 0;">Generated: {today}</p>
  </div>

  <div style="background-color: #F4F8FD; padding: 20px;">
    <h2 style="color: #1F4E79;">Key Metrics Snapshot</h2>
    <table style="width:100%; border-collapse: collapse;">
      <tr style="background-color: #2E75B6; color: white;">
        <th style="padding: 10px; text-align: left;">Metric</th>
        <th style="padding: 10px; text-align: left;">Value</th>
      </tr>
      <tr style="background-color: white;">
        <td style="padding: 10px; border-bottom: 1px solid #ddd;">Total Sales</td>
        <td style="padding: 10px; border-bottom: 1px solid #ddd;"><strong>${m['total_sales']:,.2f}</strong></td>
      </tr>
      <tr style="background-color: #f9fbfd;">
        <td style="padding: 10px; border-bottom: 1px solid #ddd;">Total Profit</td>
        <td style="padding: 10px; border-bottom: 1px solid #ddd;"><strong>${m['total_profit']:,.2f}</strong></td>
      </tr>
      <tr style="background-color: white;">
        <td style="padding: 10px; border-bottom: 1px solid #ddd;">Profit Margin</td>
        <td style="padding: 10px; border-bottom: 1px solid #ddd;"><strong>{m['profit_margin']:.2f}%</strong></td>
      </tr>
      <tr style="background-color: #f9fbfd;">
        <td style="padding: 10px; border-bottom: 1px solid #ddd;">Total Orders</td>
        <td style="padding: 10px; border-bottom: 1px solid #ddd;"><strong>{m['total_orders']:,}</strong></td>
      </tr>
      <tr style="background-color: white;">
        <td style="padding: 10px; border-bottom: 1px solid #ddd;">Top Region</td>
        <td style="padding: 10px; border-bottom: 1px solid #ddd;"><strong>{m['top_region']}</strong></td>
      </tr>
      <tr style="{loss_row_style}">
        <td style="padding: 10px; color: #c62828;">Loss Making Areas</td>
        <td style="padding: 10px; color: #c62828;"><strong>{m['loss_list']}</strong></td>
      </tr>
    </table>
  </div>

  <div style="background-color: white; padding: 20px; border-left: 4px solid #2E75B6;">
    <h2 style="color: #1F4E79;">AI Generated Business Insights</h2>
    <div style="white-space: pre-wrap; line-height: 1.7; color: #333;">
{ai_report}
    </div>
  </div>

  <div style="background-color: #1F4E79; padding: 15px; border-radius: 0 0 8px 8px; text-align: center;">
    <p style="color: #ACD4EE; margin: 0; font-size: 12px;">
      Auto-generated by the sales insight pipeline
    </p>
  </div>

</body>
</html>
"""


def build_text_email(m: dict, ai_report: str, today: str) -> str:
    return f"""
Weekly Business Insight Report
Generated: {today}
{'=' * 50}

KEY METRICS SUMMARY:
- Total Sales:    ${m['total_sales']:,.2f}
- Total Profit:   ${m['total_profit']:,.2f}
- Profit Margin:  {m['profit_margin']:.2f}%
- Total Orders:   {m['total_orders']:,}
- Top Region:     {m['top_region']}
- Loss Areas:     {m['loss_list']}

{'=' * 50}
AI GENERATED INSIGHTS:

{ai_report}

{'=' * 50}
This report was automatically generated by the sales insight pipeline.
"""


def send_email(sender_email, sender_password, receiver_email, subject, text_body, html_body):
    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = sender_email
    msg["To"] = receiver_email
    msg.attach(MIMEText(text_body, "plain"))
    msg.attach(MIMEText(html_body, "html"))

    with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
        server.login(sender_email, sender_password)
        server.sendmail(sender_email, receiver_email, msg.as_string())


def main():
    df = load_data()
    m = compute_metrics(df)
    print(format_metrics_summary(m))
    print("Step 1: Metrics calculated successfully")

    client = Groq(api_key=os.getenv("GROQ_API_KEY"))
    ai_report = generate_ai_report(client, m)
    print("Step 2: AI report generated successfully")

    today = datetime.now().strftime("%Y-%m-%d")
    report_filename = f"output/insight_report_{today}.txt"
    with open(report_filename, "w") as f:
        f.write("WEEKLY BUSINESS INSIGHT REPORT\n")
        f.write(f"Generated on: {today}\n")
        f.write("=" * 50 + "\n\n")
        f.write(ai_report)
    print(f"Step 3: Report saved to {report_filename}")

    sender_email = os.getenv("EMAIL_SENDER")
    sender_password = os.getenv("EMAIL_PASSWORD")
    receiver_email = sender_email  # sending to yourself

    text_body = build_text_email(m, ai_report, today)
    html_body = build_html_email(m, ai_report, today)

    try:
        send_email(
            sender_email,
            sender_password,
            receiver_email,
            subject=f"Weekly Business Insight Report — {today}",
            text_body=text_body,
            html_body=html_body,
        )
        print(f"Step 4: Email sent successfully! Check your inbox at {receiver_email}")
    except Exception as e:
        print(f"Email failed: {e}")

    print("\nPipeline complete! Report generated and emailed successfully.")


if __name__ == "__main__":
    main()
