import os
import smtplib
import pandas as pd
from groq import Groq
from dotenv import load_dotenv
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from datetime import datetime

# Load environment variables
load_dotenv()

# ── STEP 1: LOAD DATA & CALCULATE METRICS ──────────────────────────
df = pd.read_csv('data/superstore_cleaned.csv')

total_sales = df['Sales'].sum()
total_profit = df['Profit'].sum()
profit_margin = (total_profit / total_sales) * 100
total_orders = df['Order ID'].nunique()
total_customers = df['Customer Name'].nunique()

region_sales = df.groupby('Region')['Sales'].sum().sort_values(ascending=False)
top_region = region_sales.index[0]
top_region_sales = region_sales.iloc[0]

loss_subs = df.groupby('Sub-Category')['Profit'].sum()
loss_subs = loss_subs[loss_subs < 0].sort_values()
loss_list = ', '.join(loss_subs.index.tolist())

cat_profit = df.groupby('Category')['Profit'].sum().sort_values(ascending=False)
best_category = cat_profit.index[0]
worst_category = cat_profit.index[-1]

print("✅ Step 1: Metrics calculated successfully")

# ── STEP 2: GENERATE AI REPORT ─────────────────────────────────────
client = Groq(api_key=os.getenv("GROQ_API_KEY"))

prompt = f"""
You are a senior business analyst. Based on the following real sales data,
write a professional weekly business insight report with clear recommendations.

BUSINESS METRICS:
- Total Sales: ${total_sales:,.2f}
- Total Profit: ${total_profit:,.2f}
- Profit Margin: {profit_margin:.2f}%
- Total Orders: {total_orders:,}
- Total Customers: {total_customers:,}
- Top Region: {top_region} (${top_region_sales:,.2f} in sales)
- Best Category: {best_category}
- Worst Category: {worst_category}
- Loss Making Sub-Categories: {loss_list}

Write a report with these 4 sections:
1. Executive Summary (2-3 sentences)
2. Key Findings (3-4 bullet points)
3. Risk Areas (focus on loss-making products)
4. Recommendations (3 clear actionable steps)

Keep it professional, concise and data-driven.
"""

response = client.chat.completions.create(
    model="llama-3.3-70b-versatile",
    messages=[{"role": "user", "content": prompt}],
    temperature=0.7,
    max_tokens=1000
)

ai_report = response.choices[0].message.content
print("✅ Step 2: AI report generated successfully")

# ── STEP 3: SAVE REPORT TO FILE ────────────────────────────────────
today = datetime.now().strftime("%Y-%m-%d")
report_filename = f"output/insight_report_{today}.txt"

with open(report_filename, 'w') as f:
    f.write(f"WEEKLY BUSINESS INSIGHT REPORT\n")
    f.write(f"Generated on: {today}\n")
    f.write("=" * 50 + "\n\n")
    f.write(ai_report)

print(f"✅ Step 3: Report saved to {report_filename}")
print("\n=== REPORT PREVIEW ===\n")
print(ai_report[:500] + "...")

# ── STEP 4: SEND EMAIL REPORT ───────────────────────────────────────
sender_email = os.getenv("EMAIL_SENDER")
sender_password = os.getenv("EMAIL_PASSWORD")
receiver_email = os.getenv("EMAIL_SENDER")  # sending to yourself

# Build the email
msg = MIMEMultipart("alternative")
msg['Subject'] = f"Weekly Business Insight Report — {today}"
msg['From'] = sender_email
msg['To'] = receiver_email

# Plain text version
text_body = f"""
Weekly Business Insight Report
Generated: {today}
{'='*50}

KEY METRICS SUMMARY:
- Total Sales:    ${total_sales:,.2f}
- Total Profit:   ${total_profit:,.2f}
- Profit Margin:  {profit_margin:.2f}%
- Total Orders:   {total_orders:,}
- Top Region:     {top_region}
- Loss Areas:     {loss_list}

{'='*50}
AI GENERATED INSIGHTS:

{ai_report}

{'='*50}
This report was automatically generated by the
AI-Powered Sales Dashboard Pipeline.
"""

# HTML version — looks professional
html_body = f"""
<html>
<body style="font-family: Arial, sans-serif; max-width: 700px; margin: auto;">

  <div style="background-color: #1F4E79; padding: 20px; border-radius: 8px 8px 0 0;">
    <h1 style="color: white; margin: 0; font-size: 22px;">
      Weekly Business Insight Report
    </h1>
    <p style="color: #ACD4EE; margin: 5px 0 0;">Generated: {today}</p>
  </div>

  <div style="background-color: #F4F8FD; padding: 20px;">
    <h2 style="color: #1F4E79;">Key Metrics Snapshot</h2>
    <table style="width:100%; border-collapse: collapse;">
      <tr style="background-color: #2E75B6; color: white;">
        <th style="padding: 10px; text-align: left;">Metric</th>
        <th style="padding: 10px; text-align: left;">Value</th>
      </tr>
      <tr style="background-color: white;">
        <td style="padding: 10px; border-bottom: 1px solid #ddd;">Total Sales</td>
        <td style="padding: 10px; border-bottom: 1px solid #ddd;"><strong>${total_sales:,.2f}</strong></td>
      </tr>
      <tr style="background-color: #f9fbfd;">
        <td style="padding: 10px; border-bottom: 1px solid #ddd;">Total Profit</td>
        <td style="padding: 10px; border-bottom: 1px solid #ddd;"><strong>${total_profit:,.2f}</strong></td>
      </tr>
      <tr style="background-color: white;">
        <td style="padding: 10px; border-bottom: 1px solid #ddd;">Profit Margin</td>
        <td style="padding: 10px; border-bottom: 1px solid #ddd;"><strong>{profit_margin:.2f}%</strong></td>
      </tr>
      <tr style="background-color: #f9fbfd;">
        <td style="padding: 10px; border-bottom: 1px solid #ddd;">Total Orders</td>
        <td style="padding: 10px; border-bottom: 1px solid #ddd;"><strong>{total_orders:,}</strong></td>
      </tr>
      <tr style="background-color: white;">
        <td style="padding: 10px; border-bottom: 1px solid #ddd;">Top Region</td>
        <td style="padding: 10px; border-bottom: 1px solid #ddd;"><strong>{top_region}</strong></td>
      </tr>
      <tr style="background-color: #fff3e0;">
        <td style="padding: 10px; color: #c62828;">Loss Making Areas</td>
        <td style="padding: 10px; color: #c62828;"><strong>{loss_list}</strong></td>
      </tr>
    </table>
  </div>

  <div style="background-color: white; padding: 20px; border-left: 4px solid #2E75B6;">
    <h2 style="color: #1F4E79;">AI Generated Business Insights</h2>
    <div style="white-space: pre-wrap; line-height: 1.7; color: #333;">
{ai_report}
    </div>
  </div>

  <div style="background-color: #1F4E79; padding: 15px; border-radius: 0 0 8px 8px; text-align: center;">
    <p style="color: #ACD4EE; margin: 0; font-size: 12px;">
      Auto-generated by AI-Powered Sales Dashboard Pipeline
    </p>
  </div>

</body>
</html>
"""

# Attach both versions
msg.attach(MIMEText(text_body, "plain"))
msg.attach(MIMEText(html_body, "html"))

# Send the email
try:
    with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
        server.login(sender_email, sender_password)
        server.sendmail(sender_email, receiver_email, msg.as_string())
    print("✅ Step 4: Email sent successfully!")
    print(f"   Check your inbox at {receiver_email}")
except Exception as e:
    print(f"❌ Email failed: {e}")

print("\n🎉 Pipeline complete! Report generated and emailed successfully.")